<?php

/**
 * JobeetJobTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{

  static public $types = array(
    'full-time' => 'Full time',
    'part-time' => 'Part time',
    'freelance' => 'Freelance',
  );
 
  public function getTypes()
  {
    return self::$types;
  }

  /**
   * Returns an instance of this class.
   *
   * @return object JobeetJobTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('JobeetJob');
  }

  public function getActiveJobs()
  {
    $q = $this->createQuery('j')
    ->where('j.expires_at > ?', date('Y-m-d h:i:s', time()))
    ->orderBy('j.expires_at DESC');
 
    return $q->execute();
  }
}
