all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=jobeet-db;dbname=jobeet'
      username: jobeet
      password: jobeet
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jobeet_test'
      username: root
      password: mYsEcret

dev:
  doctrine:
    class: sfDoctrineDatabase
 
